# Generated by Django 4.1.2 on 2022-12-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('sex', models.FloatField()),
                ('bmi', models.FloatField()),
                ('children', models.FloatField()),
                ('smoker', models.FloatField()),
                ('region', models.FloatField()),
                ('charges', models.FloatField()),
            ],
        ),
    ]
