stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - source_code/insurance_course5i.csv

    outs:
    - data/raw/insurance_course5i.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/insurance_course5i.csv

    outs:
    - data/processed/train_insurance_course5i.csv
    - data/processed/test_insurance_course5i.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_insurance_course5i.csv
    - data/processed/test_insurance_course5i.csv
    - src/train_and_evaluate.py

    params:
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio

    #metrics:
    #- reports/scores.json
    #  cache: false
    #- reports/params.json
    #  cache: false
    #outs:
    #- models/model.joblib

  mlflow_config:
  artifacts_dir: artifacts
  experiment_name: ElasticNet_Expenses
  run_name: mlops
  registered_model_name: ElasticNetMedicalExpenses
  remote_server_uri: http://127.0.0.0:5000/


