base:
  project: mlops-insurance
  random_state: 20
  target_col: charges

data_source:
  s3_source: source_code/insurance_course5i.csv

load_data:
  raw_dataset_csv: data/raw/insurance_course5i.csv

split_data:
  train_path: data/processed/train_insurance_course5i.csv
  test_path: data/processed/test_insurance_course5i.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.7
      l1_ratio: 0.8

model_dir: models

reports :
  params: reports/params.json
  scores: reports/scores.json

webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: ElasticNet_Expenses_course5i
  run_name: mlops
  registered_model_name: ElasticNetMedicalExpenses
  remote_server_uri: http://ec2-13-233-129-70.ap-south-1.compute.amazonaws.com:5000/







